### ISSUE TITLE
missing images in examples documentation

### ISSUE THREAD

**Issue by cchris28** [dirac-institute/kbmod#268]
This has 4 of 7 thumbnails. Perhaps we should generate for all?
https://epyc.astro.washington.edu/~kbmod/examples/index.html

**Comment by DinoBektesevic** [comment]
Some of the notebooks need to be re-run but I didn't have the environments set up properly, or the notebook's metadata recorded an environment I had no access to.

Then, because multiple plots can be present in a single notebook, the cell whose output you want needs to be tagged with:

```yaml
"nbsphinx-thumbnail": {
    "tooltip": "Sum, mean and median stacked postage stamp."
}
```


like:

https://github.com/dirac-institute/kbmod/blame/main/notebooks/kbmod_visualize.ipynb#L249
